name: Jekyll Deploy

on:
 schedule:
  - cron: "0 * * * *"
 push:
  branches: [master]
 workflow_dispatch:

jobs:
 build:
  name: ✨ Jekyll build
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: IgorKowalczykBot/jekyll-action@master
     with:
      token: ${{ secrets.JEKYLL_WORKFLOW_TOKEN_2 }}
      target_branch: "build"
